import { qrSvg, checkInUrl } from "@/lib/qr";

/** Server-rendered QR — no client JS, no extra request. */
export async function BookingQr({ token, label }: { token: string; label: string }) {
  const svg = await qrSvg(checkInUrl(token), 148);

  return (
    <details>
      <summary className="cursor-pointer text-xs text-accent marker:content-none">
        {label}
      </summary>
      <div
        className="mt-2 inline-block rounded-md border border-line bg-white p-1.5"
        // Generated by the qrcode package from our own token — not user input.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </details>
  );
}
